# Change these first
owner: Tortoisetype # Your GitHub organization or username, where this repository lives
repo: Uptime # The name of this repository

sites:
  - name: V-eyes
    url: https://www.v-eyes.io.vn
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.v-eyes.io.vn
  baseUrl: /
  logoUrl: https://www.v-eyes.io.vn/favicon.ico
  name: V-eyes Status
  introTitle: "**V-eyes Systems Status**"
  introMessage: Real-time monitoring and uptime reporting for **V-eyes** services. We strive for 100% transparency and reliability.

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
